/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package validator;

import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form view
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoLbl = new javax.swing.JLabel();
        textField = new javax.swing.JTextField();
        btCPF = new javax.swing.JButton();
        btTelephone = new javax.swing.JButton();
        btPlate = new javax.swing.JButton();
        btUrl = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Validador");

        infoLbl.setText("Insira a cadeia a ser testada:");

        btCPF.setText("Testar cadeia como CPF");
        btCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCPFActionPerformed(evt);
            }
        });

        btTelephone.setText("Testar cadeia como número de telefone");
        btTelephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTelephoneActionPerformed(evt);
            }
        });

        btPlate.setText("Testar cadeia como placa de carro");
        btPlate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPlateActionPerformed(evt);
            }
        });

        btUrl.setText("Testar cadeia como web URL simples");
        btUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUrlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(textField)
                    .addComponent(btCPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btTelephone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btPlate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btUrl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btPlate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCPFActionPerformed
        JOptionPane.showMessageDialog(this, Validator.validateCPF(textField.getText()) ? "A cadeia é um CPF válido" : "A cadeia é um CPF inválido", "Resultado do Teste", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btCPFActionPerformed

    private void btTelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTelephoneActionPerformed
        JOptionPane.showMessageDialog(this, Validator.validatePhone(textField.getText()) ? "A cadeia é um número válido de telefone" : "A cadeia é um número inválido de telefone", "Resultado do Teste", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btTelephoneActionPerformed

    private void btPlateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPlateActionPerformed
        JOptionPane.showMessageDialog(this, Validator.validatePlate(textField.getText()) ? "A cadeia é uma placa de carro válida" : "A cadeia é uma placa de carro inválida", "Resultado do Teste", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btPlateActionPerformed

    private void btUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUrlActionPerformed
        JOptionPane.showMessageDialog(this, Validator.validateUrl(textField.getText()) ? "A cadeia é uma URL válida" : "A cadeia é uma URL inválida", "Resultado do Teste", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btUrlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCPF;
    private javax.swing.JButton btPlate;
    private javax.swing.JButton btTelephone;
    private javax.swing.JButton btUrl;
    private javax.swing.JLabel infoLbl;
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables
}
